export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const INCREASE_PRODUCT_QUANTITY_IN_CART =
  "INCREASE_PRODUCT_QUANTITY_IN_CART";
export const DECREASE_PRODUCT_QUANTITY_IN_CART =
  "DECREASE_PRODUCT_QUANTITY_IN_CART";
export const CLEAR_CART = "CLEAR_CART";
